### ISSUE TITLE
Login failed after init

### ISSUE THREAD

**Issue by RdTrxx** [gaois/terminologue#130]
Hi, 
I followed the instructions from

[](https://docs.gaois.ie/en/software/terminologue/installation)

"node init.js" gave me my login with root@localhost and a password.

But when I try to login with that credentials , I get an error with "Invalid e-mail address or password."

Regards
Volker

My environment is an docker container with node.js 23.4.0
Logs from

###### npm install
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated gauge@4.0.4: This package is no longer supported.

added 368 packages, and audited 369 packages in 8s

72 packages are looking for funding
  run `npm fund` for details

14 vulnerabilities (5 low, 6 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

###### node init.js
I have created a user account for root@localhost. The password is: <password>

###### node terminilogue.js
Process ID 79 is now listening on port number 80.

**Comment by michmech** [comment]
That does not repro on my machine. I've just tested it with a fresh installation of Terminologue and all works fine. I'm able to log in after `init,js`. So now we have to figure out what's different for you.

Are you sure you followed all instructions from [here](https://docs.gaois.ie/en/software/terminologue/installation), including renaming files etc.?

After you have run `init.js`, could you open the fie `data/terminologue.sqlite` (in an SQLite viewer such as [DB4S](https://sqlitebrowser.org/)) and see if the table `users` contains an entry for `root@localhost`?

Last but not least, are you sure you got the password right, no trailing spaces or anything?

**Comment by RdTrxx** [comment]
Hi, 
I finally found my mistake. Always in front of the Screen :-D
I use a password manager and I saves the elogin entry with a space in front of the email " root@localhost".
So password and everything was fine but the login was simply wrong!
Thanx for your support!
