### ISSUE TITLE
Áis chun foinse nua a chruthú ón bhfuinneog eagarthóireachta

### ISSUE THREAD

**Issue by oraghalb** [gaois/terminologue#18]

**Comment by michmech** [comment]
Déanta le commit 3c8f0dd.

Eolas breise: is féidir é seo a chur i bhfeidhm go héasca ar na meiteashonraí eile.

**Comment by michmech** [comment]
Le commit 1569c11, tá sé curtha i bhfeidhm ar na meiteashonraí eile.
