### ISSUE TITLE
Teachtaireacht earráide mhíthreorach

### ISSUE THREAD

**Issue by oraghalb** [gaois/terminologue#21]
Má aighnítear seoladh ríomhphoist atá in úsáid [anseo](https://www.terminologue.org/signup/), faightear an teachtaireacht earráide 'Seoladh ríomhphoist mícheart.'/'Incorrect e-mail address.' Ba cheart an teachtaireacht earráide 'Seoladh ríomhphoist in úsáid.'/'E-mail address in use.' a fháil.

**Comment by michmech** [comment]
Tá sé seo ceartaithe anois.
