### ISSUE TITLE
Gach iontráil (uasteorainn 1,000 iontráil) a chur ar lch amháin sa leagan oiriúnach le priontáil ar an eislíon.

### ISSUE THREAD

**Issue by oraghalb** [gaois/terminologue#27]

**Comment by michmech** [comment]
Níl sé éasca seo a dhéanamh. An dá leathanach sin, an leathanach le priontáil agus an leathanach don scáileán, is ionann iad: níl ann ach dhá radharc CSS ar an leathanach céanna.

Réiteach éasca amháin a rithfeadh leat, b'fhéidir, ná líon na n-iontrálacha per leathanach a athrú scun scan ó 100 (mar atá anois) go 1,000. Ní mholfainn sin, áfach. Tá mé tar éis é a thástáil, cuireann sé moill inbhraiste ar an lódáil agus reonn se an brabhsálaí ar feadh píosa (gairid ach inbhraiste).

Is dócha gurbh é an réiteach a b'fhearr ná áis nua a chruthú sa chomhéadan a chuirfeadh ar chumas an úsáideora líon na n-iontrálacha per leathanach a shaincheapadh. Ansin bheadh daoine in ann míle iontráil a chur ar an aon leathanach amháin más maith leo, má tá siad sásta an mhoill agus an reo a fhulaingt.

In Screeenful a bheadh an t-athrú seo déanta, mar sin bheadh an áis le fáil gach áit a bhfuil Screenful (i bprionsabal).

Ba cheart go mbeadh uasteorainn chrua éigin ann ar eagla na heagla, cibé ar bith: cúpla míle, déarfainn.

**Comment by michmech** [comment]
OK, déanfaidh m\e seo.

**Comment by michmech** [comment]
Tá sé seo déanta anois, agus i bhfeidhm sa dá shuiteán.
