### ISSUE TITLE
Áis easpórtála téarmaí GA/EN ón eislíon.

### ISSUE THREAD

**Issue by oraghalb** [gaois/terminologue#28]
Áis a ghineann 'leagan oiriúnach le cóipeáil isteach i dtábla Word' den eislíon? Leagan lom (le formáidiú) le dhá cholún (A: liosta téarmaí GA le noda gramadaí; B: liosta téarmaí EN le noda gramadaí) arbh fhéidir a chóipeáil isteach i dtábla Word (miontuairiscí chruinnithe an CT).

**Comment by michmech** [comment]
Gaolta le #2.
