### ISSUE TITLE
Spás gan leithead a úsáid chun timfhilleadh a éascú i dtéarmaí fada gan spás ná fleiscín.

### ISSUE THREAD

**Issue by oraghalb** [gaois/terminologue#43]
https://www.tearma.ie/q/methylimino/

**Comment by michmech** [comment]
Tá sé seo ceartaithe anois le commit 67bb8961ac759d529d6950cc3e95494f89a2d134.
Tá an ceartúchán uaslódáilte chuig terminologue.org agus eag.tearma.ie.
