### ISSUE TITLE
Áis liostaithe/brabhsála poiblí

### ISSUE THREAD

**Issue by oraghalb** [gaois/terminologue#79]
- Áis a liostaíonn gach iontráil i gcnuasach go haibítreach ar an gcomhéadan poiblí.
- Torthaí briste ina leathanaigh.
- Torthaí insórtáilte de réir teanga.
- Torthaí inscagtha de réir réimse.

**Comment by michmech** [comment]
Tá sé seo á fhorbairt agam sa bhrainse `better-public-ui`.

**Comment by michmech** [comment]
Déanta agus beo ar `www.terminologue.org` anois.
